name: Build GangstaPatch

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write

    strategy:
      matrix:
        configuration: [Release]
        platform: [x86]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        choco install -y llvm
        choco install -y cmake

    - name: Configure and Build
      run: |
        git clone https://github.com/STWIY/SDK.git
        mkdir build
        cd build
        cmake -T ClangCL -A Win32 -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ..
        cmake --build . --config ${{ matrix.configuration }} -j 14
   
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: GangstaPatch
        path: Release/Release/GangstaPatch.asi

    - name: Get Release ID
      id: get_release
      run: |
        $token = "${{ secrets.GITHUB_TOKEN }}"
        $release = Invoke-RestMethod -Uri "https://api.github.com/repos/STWIY/GangstaPatch/releases/tags/continuous" -Headers @{ Authorization = "token $token" }
        $release_id = $release.id
        Write-Host "::set-output name=release_id::$release_id"
      shell: pwsh

    - name: Delete Existing Asset
      run: |
        $token = "${{ secrets.GITHUB_TOKEN }}"
        $assets = Invoke-RestMethod -Uri "https://api.github.com/repos/STWIY/GangstaPatch/releases/${{ steps.get_release.outputs.release_id }}/assets" -Headers @{ Authorization = "token $token" }
        foreach ($asset in $assets) {
          Invoke-RestMethod -Uri "https://api.github.com/repos/STWIY/GangstaPatch/releases/assets/$($asset.id)" -Method Delete -Headers @{ Authorization = "token $token" }
        }
      shell: pwsh

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: https://uploads.github.com/repos/STWIY/GangstaPatch/releases/${{ steps.get_release.outputs.release_id }}/assets?name=GangstaPatch.asi
        asset_path: Release/Release/GangstaPatch.asi
        asset_name: GangstaPatch.asi
        asset_content_type: application/octet-stream
