name: Build GangstaPatch

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        platform: [x86]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Clang
      uses: llvm/llvm-project@main
      with:
        clang-version: '14.0.0' # Specify the version you need

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Dependencies
      run: |
        # Commands to install SDK dependencies:
        # git clone https://github.com/STWIY/SDK.git
        # cd sdk
        # ./install-script.sh

    - name: Configure and Build
      run: |
        # Configure the environment for Clang
        set CC=clang
        set CXX=clang++

        # Build the project using MSBuild
        msbuild myproject.sln /p:Configuration=%{{ matrix.configuration }} /p:Platform=%{{ matrix.platform }}
