name: Build GangstaPatch

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        platform: [x86]

    steps:
    - name: Checkout other repository
      uses: actions/checkout@v2
      with:
        repository: STWIY/SDK
        ref: master

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        choco install -y llvm
        choco install -y cmake

    - name: Configure and Build
      run: |
        dir
        mkdir build
        cd build
        cmake -T ClangCL -A Win32 -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} ..
        cmake --build . --config ${{ matrix.configuration }} -j 14
        
